### ISSUE TITLE
Support bundling of short options for GNU getopt compatibility

### ISSUE THREAD

**Issue by mjradwin** [JoakimSoderberg/cargo#13]
We'd like to be able to use cargo in our project [hebcal](https://github.com/hebcal/hebcal) to replace GNU getopt. Could you support bundling of short options together?

In the `cargo.c` source, there is a TODO which mentions that `-vaet` should be interpreted the same as `-v -a -e -t`.

Here's a test program to demonstrate that the feature doesn't work yet.

```
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include "cargo.h"

int main(int argc, char **argv) {
    cargo_t cargo;
    int ret = 0;
    int opta = 0, optb = 0, optc = 0;

    if (cargo_init(&cargo, 0, "%s", argv[0])) {
        fprintf(stderr, "Failed to init command line parsing\n");
        return -1;
    }

    ret |= cargo_add_option(cargo, 0, "-a", "Option A", "b", &opta);
    ret |= cargo_add_option(cargo, 0, "-b", "Option B", "b", &optb);
    ret |= cargo_add_option(cargo, 0, "-c", "Option C", "b", &optc);

    assert(ret == 0);

    if (cargo_parse(cargo, 0, 1, argc, argv)) return -1;

    if (opta) printf("Option A is set %d\n", opta);
    if (optb) printf("Option B is set %d\n", optb);
    if (optc) printf("Option C is set %d\n", optc);

    cargo_destroy(&cargo);

    return 0;
}
```

Usage:

```
$ ./bundling -h
Usage: bundling [--help] [-a] [-b] [-c]


Options:
    -h, --help  Show this help
    -a          Option A
    -b          Option B
    -c          Option C
$
```

Options specified separately:

```
    $ ./bundling -a -c
    Option A is set 1
    Option C is set 1
    $
```

Options specified bundled together:

```
    $ ./bundling -ac
    Usage: bundling [--help] [-a] [-b] [-c]
    Unknown options:
    -ac 
    ~~~
    -ac  (Did you mean -a)?
    $
```

Ideally we'd like bundling to work the way [Perl's Getopt::Long bundling](http://perldoc.perl.org/Getopt/Long.html#Bundling) works. An excerpt from their documentation:

> Configured this way, single-character options can be bundled but long options must always start with a double dash `--` to avoid ambiguity. For example, when `vax`, `a`, `v` and `x` are all valid options,
>    `-vax`
> will set `a`, `v` and `x`, but
>    `--vax`
> will set `vax`.

**Comment by JoakimSoderberg** [comment]
Hello, fun to see you're using cargo. Yes I'm planning to add support for that. Right now I have a "special case" for when you specify the _same_ variable multiple times, so:

`-v -v -v` can also be written as `-vvv` so it would make sense for other short names like this.

However I cannot promise when I will get to this, I'm kind of busy with other things at the moment.

**Comment by mjradwin** [comment]
Thanks for the quick reply. We will look forward to this feature whenever you find time to implement it!

**Comment by JoakimSoderberg** [comment]
Hello @mjradwin 

I have now implemented this with bd303ebb655f97a792ee8cc9623f2b22801544ea:

``` bash
$ bin/cargo_ex_flags -a -c
Option A is set 1
Option C is set 1

$ bin/cargo_ex_flags -ac
Option A is set 1
Option C is set 1
```

**Comment by JoakimSoderberg** [comment]
Reopen the issue if you find any bugs :)

**Comment by mjradwin** [comment]
Thanks. I will give it a whirl and report back.

**Comment by mjradwin** [comment]
Thanks for the feature - it's not 100% compatible with getopt_long yet.

If you have a short option that takes a non-boolean argument (an int or a string, for example), a getopt compatible parser will let you say `./bin/bundling -ace foo` which should be interpreted as `-a -c -e foo`.

Here's an updated test program:

``` c
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include "cargo.h"

int main(int argc, char **argv) {
    cargo_t cargo;
    int ret = 0;
    int opta = 0, optb = 0, optc = 0;
    int optd = 0;
    char *opte = NULL;

    if (cargo_init(&cargo, 0, "%s", argv[0])) {
        fprintf(stderr, "Failed to init command line parsing\n");
        return -1;
    }

    ret |= cargo_add_option(cargo, 0, "--apple -a", "Option A", "b", &opta);
    ret |= cargo_add_option(cargo, 0, "--banana -b", "Option B", "b", &optb);
    ret |= cargo_add_option(cargo, 0, "--coconut -c", "Option C", "b", &optc);
    ret |= cargo_add_option(cargo, 0, "--durian -d", "Option D", "i", &optd);
    ret |= cargo_add_option(cargo, 0, "--eggplant -e", "Option E", "s", &opte);

    assert(ret == 0);

    if (cargo_parse(cargo, 0, 1, argc, argv)) return -1;

    if (opta) printf("Option A is set %d\n", opta);
    if (optb) printf("Option B is set %d\n", optb);
    if (optc) printf("Option C is set %d\n", optc);
    if (optd) printf("Option D is set %d\n", optd);
    if (opte) printf("Option E is set %s\n", opte);

    cargo_destroy(&cargo);

    return 0;
}
```

And output

```
     $ ./bin/bundling  -ae foo -c
     Usage: bundling [--help] [--apple] [--banana] [--coconut] [--durian DURIAN]
                     [--eggplant EGGPLANT]
     Unknown options:
     -ae foo -c 
     ~~~
     -ae  (Did you mean -a)?
```
